### ISSUE TITLE
🐛 [Bug Report] Azshara - Azuregos

### ISSUE THREAD

**Issue by Auxil3300** [Valkirie/rochenoire-issues#3]
## 🐛 Bugreport
Azshara - Azuregos

### Expected behavior
Azuregos is a world boss, the zone needs to be upscaled to 70, hes not in a subzone like the world dragons sadly so it cannot be done in the same way as them

## recommended result

Change azshara and its sub zones to 35-70

**Comment by Valkirie** [comment]
`UPDATE scale_zone SET LevelRangeMax = 70 WHERE areaId = 16;`
